# version: 2.1
# orbs:
#   node: circleci/node@8.10.0 #3.0.0
# workflows:
#   node-tests:
#     jobs:
#       - node/test

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.0.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
